version: '3'
services:
  container-configserver:
    image: mcr.microsoft.com/devcontainers/java:1-21-bullseye
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    links:
      - container-serviceregistry
      - container-apigateway
      - container-aleatorio
  container-serviceregistry:
    image: mcr.microsoft.com/devcontainers/java:1-21-bullseye
    volumes:
      - .:/workspace:cached
    command: sleep infinity
  container-apigateway:
    image: mcr.microsoft.com/devcontainers/java:1-21-bullseye
    volumes:
      - .:/workspace:cached
    command: sleep infinity
  container-aleatorio:
    image: mcr.microsoft.com/devcontainers/java:1-21-bullseye
    volumes:
      - .:/workspace:cached
    command: sleep infinity
